# Generated by Django 4.0.6 on 2022-08-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_review_review_user_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
