# Generated by Django 4.0.6 on 2022-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_review_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='times',
            field=models.IntegerField(default=1),
        ),
    ]
